### PR TITLE
Print VK_MEMORY_PROPERTY_*_BIT flags more nicely.

### PR DESCRIPTION
**Pull request by chisophugis**
Hopefully the print_flags function is useful for printing some other
fields too.

### CODE REVIEW

**Comment by karl-lunarg** [comment]
This may have been handled by https://github.com/LunarG/VulkanTools/issues/44

**Comment by chisophugis** [comment]
It looks like it was: https://github.com/LunarG/VulkanTools/blob/master/demos/vulkaninfo.c#L1024
(wow, just yesterday! https://github.com/LunarG/VulkanTools/commit/3c877cdec3dc56f422fcc2e6ffa11dd7cd666eb0)

What is the relationship between LunarG/VulkanSamples and LunarG/VulkanTools? I assume that VulkanTools upstream from VulkanSamples? What is the integration process? I'm curious why vulkaninfo.c is duplicated across them.

**Comment by karl-lunarg** [comment]
LunarG/VulkanSamples and LunarG/VulkanTools both are downstream from KhronosGroup/Vulkan-LoaderAndValidationLayers.   The VulkanTools README.md explains this pretty well; VulkanSamples not so much.  (We will fix).

The commit  LunarG/VulkanTools@3c877cd actually came from Vulkan-LoaderAndValidation layers in response to an Issue on VulkanTools.

Since the upstream source is in LVL, the work was done there and is later propagated to VT and VS.

The overlap between your PR and https://github.com/LunarG/VulkanTools/issues/44 was just a (happy) coincidence.

**Comment by chisophugis** [comment]
Thanks for the info. That clears things up.

**Pull request closed without merging**
