### PR TITLE
Add support for running samples on iOS and macOS via MoltenVK

### PR DESCRIPTION
**Pull request by billhollings**
As the title indicates, these updates add support for MoltenVK, to allow the VulkanSamples to be run on the iOS and macOS platforms.

Although I have been very careful, I do not have access to other Vulkan platforms to validate that these updates do not affect those platforms.

I would appreciate it if others could run on the other platforms and report if there are any issues.

### CODE REVIEW

**Comment by Tony-LunarG** [comment]
I checked this out on Linux and Windows and it all looks fine, with a couple of small requests. If you read through the CONTRIBUTING.md file, it explains that this VulkanSamples repo is actually downstream of the Vulkan-LoaderAndValidationLayers repo, and not all files are managed here.  cube.c is one of those files, so could you remove cube changes from this PR and create a PR for the cube changes here:
https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers

Also could you squash your commits into fewer, or ideally one commit that looks something like:
samples: Add support for iOS & OSX through MoltenVK.

Thanks!

**Comment by billhollings** [comment]
I'll sort out the `cube.c` source and others like that.

But why do you want to squash everything into one commit? That seems counter to Git philosophy. I'm used to being asked to create smaller commits!

**Comment by billhollings** [comment]
@Tony-LunarG 

Is there an easy way to tell which files are sourced from the loader and layers repo? I can't see any way of telling from this repo which files are sourced somewhere else upstream.

**Comment by billhollings** [comment]
@Tony-LunarG 

Per your request...`cube.c` has been [submitted via a PR](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/1483) to the `Vulkan-LoaderAndValidationLayers` repo. The version of `cube.c` in this PR is now aligned with that repo.

Regarding squashing...I think the easiest way to accomplish that is for you to [choose to squash during the merge](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits) of this PR.

**Comment by Tony-LunarG** [comment]
Thanks for addressing my suggestions.  As for documenting which files come from upstream, I don't think it is documented anywhere, and a good to-do for me and the VulkanTools owner would be to create a manifest document describing what comes from where.  FYI, with a few exceptions (like CMake files), if it exists in Vulkan-LayersAndValidationLayers, that's where it comes from.   API-Samples, Layer-Samples, Sample-Programs, samples-images, and Utilities are all unique to VulkanSamples.

**Pull request merged**
