### PR TITLE
Use precompiled layers

### PR DESCRIPTION
**Pull request by ggfan**
for discussion only: @courtney-g @courtney-lunarg please take a look, thanks!

### CODE REVIEW

**Comment by karl-lunarg** [comment]
What is the reason for all the renaming?  If these files are renamed, the Tutorial needs to change as well.

**Comment by ggfan** [comment]
Android could take a number  at the beginning of the package name ( like 01_something), it has to start with a letter, [a-z]01_...;  with a BIG T in the front of it, you still get your tutorial in front of other samples with alphabetic order.

right now now of these could compile for android I think

**Comment by karl-lunarg** [comment]
OK.  Well it is a bummer to need to change the names again.  But if they do change, then the references in the tutorial text need to follow.  For example:

```
markdown/01-init_instance.md:Code file for this section is `01-init_instance.cpp`
markdown/01-init_instance.md:Find the `01-init_instance.cpp` program in the `API-Samples` folder
markdown/01-init_instance.md:Take a look at the `01-init_instance.cpp` source code and find the
```

**Comment by ggfan** [comment]
yeah, please list all of them related,  I will change them: it still far out, planned changes:
- use cmake rather than experimental for android
- remove all of those one-project-one-directory model, and put them back to its origin where all source files sitting in one directory -- cmake could handle it

either in one CL or in a separate CL is open, so please let me know, thanks

**Comment by courtney-g** [comment]
@ggfan - When you say that Android can't have a number at the beginning of the file name, can you be more specific? E.g. is this a limitation on APKs or a general limitation that applies to any binary on Android?
I suspect it may be the former (an APK rule), in which case I have to ask, are we putting these samples into APKs? If not, I don't think that the Android shell cares about the naming. That could avoid some thrash.

**Comment by ggfan** [comment]
it is with APK name, it could not start with a number after dot ("."), come info is here:  https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html.

**Comment by karl-lunarg** [comment]
@ggfan @courtney-g Can you guys close on this and indicate the next step?

**Comment by ggfan** [comment]
I thought the branch has been merged, let me connect with Courtney now  thanks

**Pull request closed without merging**
