### PR TITLE
Retry for Android Studio/Gradle 3.4.1 build

### PR DESCRIPTION
**Pull request by ggfan**
2 minor changes:

-  Update gradle plugin version to 3.4.1
-  Use new way to retrieve ndkDir: future Android Studio 3.5 compliant when side-by-side ndk arrives

Tested on Linux

### CODE REVIEW

**Comment by Tony-LunarG** [comment]
LGTM - but not sure why it says branch can't be rebased.  I was able to do it locally.

**Comment by ggfan** [comment]
let me re-do it: do not merge it yet.

**Comment by Tony-LunarG** [comment]
The patch referenced is just the "Update Android build..." commit and doesn't have the changes from "Merge remote-tracking branch..." in API-Samples/CMakeLists.txt  Do we need the changes to CMakeLists.txt?

**Comment by Tony-LunarG** [comment]
Pushed.

**Pull request closed without merging**
